name: OpenshiftLabelingController
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: OpenshiftLabelingController
      TAGS: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup S2i and Build container image
      - name: Setup and Build
        id: build_image
        uses: redhat-actions/s2i-build@v2
        with:
          path_context: '.'
          # Builder image for a java project
          builder_image: 'registry.access.redhat.com/ubi8/python-39:1-73.1665597535'
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}


