name: OpenshiftLabelingController
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: openshiftlabelingcontroller
      TAGS: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup S2i and Build container image
      - name: Setup and Build
        id: build_image
        uses: redhat-actions/s2i-build@v2
        with:
          path_context: '.'
          # Builder image for a java project+
          builder_image: 'registry.fedoraproject.org/f35/python3'
          # builder_image: 'registry.access.redhat.com/ubi8/python-39:1-73.1665597535'
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }} latest


      # Push Image to Quay registry
      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: harbor.k3s.filice.eu/library
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
          
          
